### ISSUE TITLE
distribution has a perl prereq of 5.021008

### ISSUE THREAD

**Issue by karenetheridge** [ido50/mccs#3]
This is because `[MinimumPerl]` is finding something interesting in one of the css files.

To exclude it, you need to modify MinimumPerl with a custom filefinder:

```
[FileFinder::Filter / TestFiles_no_CSS]
finder = :TestFiles
skip = \.css$

[MinimumPerl]
test_finder = TestFiles_no_CSS
```

However, since `[MinimumPerl]` is being brought in through your plugin bundle, you need to do things a little differently: modify your bundle to compose the Dist::Zilla::Role::PluginBundle::PluginRemover and Dist::Zilla::Role::PluginBundle::Config::Slicer roles, then do this in dist.ini:

```
; define the filefinder as before
[@IDOPEREL]
MinimumPerl.test_finder = TestFiles_no_CSS
```

**Comment by ido50** [comment]
Thanks for the info. Just a question though, I don't see where the distribution is showing perl 5.021008 as the minimum required version. Both the Makefile.PL and the META.json file show 5.006.

**Comment by karenetheridge** [comment]
Running 'dzil build' on the repository at the time I created the issue would result in a perl prereq of 5.021008, because the .css file was being scanned by the `[MinimumPerl]` plugin.

You can see it directly by running `perlver --blame` on the file.
